---
title: "Project Background"
author:
  - name: Hui-Chia HungWen
    url: https://example.com/norajones
date: 07-13-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Project Proposal Background
Taiwan’s house prices continue to rise since many years ago, especially in the capital city - Taipei. Taipei is a city where has more job opportunities than other cities in Taiwan.
Buying a home remains unaffordable for most young Taiwanese. An average household in Taipei needs to pay two-thirds of its income for a mortgage loan. Most of the young adult who works in Taipei would buy/rent a house in neighbor cities of Taipei, and commute by car/bus/ train for 30 min to 1 hour every workday. It causes the house price in neighboring cities to continually increase.

**Keelung**, the city where I currently live, is one of the neighboring cities of Taipei but also the farthest one compares to other neighboring cities. I would like to analyze the house price changes in Keelung during these five years.

# Goals

- Keelung House price analysis

- Overall Price increase?

- County Average house price differences?
